
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]
  included_files = ["presets.json"]
  
[[redirects]]
  from = "/api/library"
  to = "/.netlify/functions/library"
  status = 200

[[redirects]]
  from = "/api/library/*"
  to = "/.netlify/functions/library/:splat"
  status = 200
